# Generated by Django 3.2.12 on 2022-04-30 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_alter_movie_director'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'permissions': (('can_change_director', 'Can Change director'),)},
        ),
    ]
